# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TT.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TextField = QtWidgets.QLabel(self.centralwidget)
        self.TextField.setGeometry(QtCore.QRect(540, 120, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.TextField.setFont(font)
        self.TextField.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(94, 110, 184);")
        self.TextField.setText("")
        self.TextField.setObjectName("TextField")
        self.TextTyped = QtWidgets.QLabel(self.centralwidget)
        self.TextTyped.setGeometry(QtCore.QRect(30, 120, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.TextTyped.setFont(font)
        self.TextTyped.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(149, 160, 255);")
        self.TextTyped.setText("")
        self.TextTyped.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TextTyped.setObjectName("TextTyped")
        self.BackGround = QtWidgets.QLabel(self.centralwidget)
        self.BackGround.setGeometry(QtCore.QRect(-10, -30, 1161, 671))
        self.BackGround.setStyleSheet("background-color: rgb(124, 133, 216);\n"
"")
        self.BackGround.setText("")
        self.BackGround.setObjectName("BackGround")
        self.KeyBoard = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard.setGeometry(QtCore.QRect(110, 270, 901, 311))
        self.KeyBoard.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard.setText("")
        self.KeyBoard.setObjectName("KeyBoard")
        self.SpaceBar = QtWidgets.QLabel(self.centralwidget)
        self.SpaceBar.setGeometry(QtCore.QRect(370, 520, 351, 51))
        self.SpaceBar.setStyleSheet("background-color: rgb(201, 225, 255);")
        self.SpaceBar.setText("")
        self.SpaceBar.setObjectName("SpaceBar")
        self.Two = QtWidgets.QLabel(self.centralwidget)
        self.Two.setGeometry(QtCore.QRect(240, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Two.setFont(font)
        self.Two.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);\n"
"")
        self.Two.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Two.setObjectName("Two")
        self.One = QtWidgets.QLabel(self.centralwidget)
        self.One.setGeometry(QtCore.QRect(180, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.One.setFont(font)
        self.One.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.One.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.One.setObjectName("One")
        self.tilde = QtWidgets.QLabel(self.centralwidget)
        self.tilde.setGeometry(QtCore.QRect(120, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.tilde.setFont(font)
        self.tilde.setStyleSheet("color: rgb(155, 164, 172);")
        self.tilde.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.tilde.setObjectName("tilde")
        self.Backspace = QtWidgets.QLabel(self.centralwidget)
        self.Backspace.setGeometry(QtCore.QRect(900, 280, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Backspace.setFont(font)
        self.Backspace.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.Backspace.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Backspace.setObjectName("Backspace")
        self.Tab = QtWidgets.QLabel(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(120, 340, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Tab.setFont(font)
        self.Tab.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.Tab.setAlignment(QtCore.Qt.AlignCenter)
        self.Tab.setObjectName("Tab")
        self.Backslash = QtWidgets.QLabel(self.centralwidget)
        self.Backslash.setGeometry(QtCore.QRect(920, 340, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Backslash.setFont(font)
        self.Backslash.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.Backslash.setAlignment(QtCore.Qt.AlignCenter)
        self.Backslash.setObjectName("Backslash")
        self.CAPS = QtWidgets.QLabel(self.centralwidget)
        self.CAPS.setGeometry(QtCore.QRect(120, 400, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CAPS.setFont(font)
        self.CAPS.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.CAPS.setAlignment(QtCore.Qt.AlignCenter)
        self.CAPS.setObjectName("CAPS")
        self.Enter = QtWidgets.QLabel(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(890, 400, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Enter.setFont(font)
        self.Enter.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.Enter.setAlignment(QtCore.Qt.AlignCenter)
        self.Enter.setObjectName("Enter")
        self.LShift = QtWidgets.QLabel(self.centralwidget)
        self.LShift.setGeometry(QtCore.QRect(120, 460, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LShift.setFont(font)
        self.LShift.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.LShift.setAlignment(QtCore.Qt.AlignCenter)
        self.LShift.setObjectName("LShift")
        self.RShift = QtWidgets.QLabel(self.centralwidget)
        self.RShift.setGeometry(QtCore.QRect(860, 460, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RShift.setFont(font)
        self.RShift.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.RShift.setAlignment(QtCore.Qt.AlignCenter)
        self.RShift.setObjectName("RShift")
        self.Grave = QtWidgets.QLabel(self.centralwidget)
        self.Grave.setGeometry(QtCore.QRect(120, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(36)
        self.Grave.setFont(font)
        self.Grave.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(155, 164, 172);")
        self.Grave.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Grave.setObjectName("Grave")
        self.Three = QtWidgets.QLabel(self.centralwidget)
        self.Three.setGeometry(QtCore.QRect(300, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Three.setFont(font)
        self.Three.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.Three.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Three.setObjectName("Three")
        self.Four = QtWidgets.QLabel(self.centralwidget)
        self.Four.setGeometry(QtCore.QRect(360, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Four.setFont(font)
        self.Four.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.Four.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Four.setObjectName("Four")
        self.Five = QtWidgets.QLabel(self.centralwidget)
        self.Five.setGeometry(QtCore.QRect(420, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Five.setFont(font)
        self.Five.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.Five.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Five.setObjectName("Five")
        self.Six = QtWidgets.QLabel(self.centralwidget)
        self.Six.setGeometry(QtCore.QRect(480, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Six.setFont(font)
        self.Six.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.Six.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Six.setObjectName("Six")
        self.Seven = QtWidgets.QLabel(self.centralwidget)
        self.Seven.setGeometry(QtCore.QRect(540, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Seven.setFont(font)
        self.Seven.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.Seven.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Seven.setObjectName("Seven")
        self.Eight = QtWidgets.QLabel(self.centralwidget)
        self.Eight.setGeometry(QtCore.QRect(600, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Eight.setFont(font)
        self.Eight.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.Eight.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Eight.setObjectName("Eight")
        self.Nine = QtWidgets.QLabel(self.centralwidget)
        self.Nine.setGeometry(QtCore.QRect(660, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Nine.setFont(font)
        self.Nine.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.Nine.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Nine.setObjectName("Nine")
        self.Zero = QtWidgets.QLabel(self.centralwidget)
        self.Zero.setGeometry(QtCore.QRect(720, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Zero.setFont(font)
        self.Zero.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Zero.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Zero.setObjectName("Zero")
        self.Minus = QtWidgets.QLabel(self.centralwidget)
        self.Minus.setGeometry(QtCore.QRect(780, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Minus.setFont(font)
        self.Minus.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Minus.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Minus.setObjectName("Minus")
        self.Equality = QtWidgets.QLabel(self.centralwidget)
        self.Equality.setGeometry(QtCore.QRect(840, 280, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Equality.setFont(font)
        self.Equality.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Equality.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Equality.setObjectName("Equality")
        self.Bracket2 = QtWidgets.QLabel(self.centralwidget)
        self.Bracket2.setGeometry(QtCore.QRect(860, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Bracket2.setFont(font)
        self.Bracket2.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Bracket2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Bracket2.setObjectName("Bracket2")
        self.Bracket1 = QtWidgets.QLabel(self.centralwidget)
        self.Bracket1.setGeometry(QtCore.QRect(800, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Bracket1.setFont(font)
        self.Bracket1.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Bracket1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Bracket1.setObjectName("Bracket1")
        self.P = QtWidgets.QLabel(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(740, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.P.setFont(font)
        self.P.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.P.setAlignment(QtCore.Qt.AlignCenter)
        self.P.setObjectName("P")
        self.O = QtWidgets.QLabel(self.centralwidget)
        self.O.setGeometry(QtCore.QRect(680, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.O.setFont(font)
        self.O.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.O.setAlignment(QtCore.Qt.AlignCenter)
        self.O.setObjectName("O")
        self.I = QtWidgets.QLabel(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(620, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.I.setFont(font)
        self.I.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.I.setAlignment(QtCore.Qt.AlignCenter)
        self.I.setObjectName("I")
        self.U = QtWidgets.QLabel(self.centralwidget)
        self.U.setGeometry(QtCore.QRect(560, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.U.setFont(font)
        self.U.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.U.setAlignment(QtCore.Qt.AlignCenter)
        self.U.setObjectName("U")
        self.Y = QtWidgets.QLabel(self.centralwidget)
        self.Y.setGeometry(QtCore.QRect(500, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Y.setFont(font)
        self.Y.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Y.setObjectName("Y")
        self.T = QtWidgets.QLabel(self.centralwidget)
        self.T.setGeometry(QtCore.QRect(440, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.T.setFont(font)
        self.T.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.T.setAlignment(QtCore.Qt.AlignCenter)
        self.T.setObjectName("T")
        self.R = QtWidgets.QLabel(self.centralwidget)
        self.R.setGeometry(QtCore.QRect(380, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.R.setFont(font)
        self.R.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.R.setAlignment(QtCore.Qt.AlignCenter)
        self.R.setObjectName("R")
        self.E = QtWidgets.QLabel(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(320, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.E.setFont(font)
        self.E.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.E.setAlignment(QtCore.Qt.AlignCenter)
        self.E.setObjectName("E")
        self.W = QtWidgets.QLabel(self.centralwidget)
        self.W.setGeometry(QtCore.QRect(260, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.W.setFont(font)
        self.W.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.W.setAlignment(QtCore.Qt.AlignCenter)
        self.W.setObjectName("W")
        self.Q = QtWidgets.QLabel(self.centralwidget)
        self.Q.setGeometry(QtCore.QRect(200, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Q.setFont(font)
        self.Q.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Q.setAlignment(QtCore.Qt.AlignCenter)
        self.Q.setObjectName("Q")
        self.A = QtWidgets.QLabel(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(230, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.A.setFont(font)
        self.A.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setObjectName("A")
        self.D = QtWidgets.QLabel(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(350, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.D.setFont(font)
        self.D.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.D.setAlignment(QtCore.Qt.AlignCenter)
        self.D.setObjectName("D")
        self.S = QtWidgets.QLabel(self.centralwidget)
        self.S.setGeometry(QtCore.QRect(290, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.S.setFont(font)
        self.S.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.S.setAlignment(QtCore.Qt.AlignCenter)
        self.S.setObjectName("S")
        self.G = QtWidgets.QLabel(self.centralwidget)
        self.G.setGeometry(QtCore.QRect(470, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.G.setFont(font)
        self.G.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.G.setAlignment(QtCore.Qt.AlignCenter)
        self.G.setObjectName("G")
        self.F = QtWidgets.QLabel(self.centralwidget)
        self.F.setGeometry(QtCore.QRect(410, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.F.setFont(font)
        self.F.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.F.setAlignment(QtCore.Qt.AlignCenter)
        self.F.setObjectName("F")
        self.H = QtWidgets.QLabel(self.centralwidget)
        self.H.setGeometry(QtCore.QRect(530, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.H.setFont(font)
        self.H.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.H.setAlignment(QtCore.Qt.AlignCenter)
        self.H.setObjectName("H")
        self.J = QtWidgets.QLabel(self.centralwidget)
        self.J.setGeometry(QtCore.QRect(590, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.J.setFont(font)
        self.J.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.J.setAlignment(QtCore.Qt.AlignCenter)
        self.J.setObjectName("J")
        self.K = QtWidgets.QLabel(self.centralwidget)
        self.K.setGeometry(QtCore.QRect(650, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.K.setFont(font)
        self.K.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.K.setAlignment(QtCore.Qt.AlignCenter)
        self.K.setObjectName("K")
        self.L = QtWidgets.QLabel(self.centralwidget)
        self.L.setGeometry(QtCore.QRect(710, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.L.setFont(font)
        self.L.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.L.setAlignment(QtCore.Qt.AlignCenter)
        self.L.setObjectName("L")
        self.Semicolon = QtWidgets.QLabel(self.centralwidget)
        self.Semicolon.setGeometry(QtCore.QRect(770, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Semicolon.setFont(font)
        self.Semicolon.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Semicolon.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Semicolon.setObjectName("Semicolon")
        self.Quote = QtWidgets.QLabel(self.centralwidget)
        self.Quote.setGeometry(QtCore.QRect(830, 400, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Quote.setFont(font)
        self.Quote.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Quote.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Quote.setObjectName("Quote")
        self.Z = QtWidgets.QLabel(self.centralwidget)
        self.Z.setGeometry(QtCore.QRect(260, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Z.setFont(font)
        self.Z.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Z.setObjectName("Z")
        self.V = QtWidgets.QLabel(self.centralwidget)
        self.V.setGeometry(QtCore.QRect(440, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.V.setFont(font)
        self.V.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.V.setAlignment(QtCore.Qt.AlignCenter)
        self.V.setObjectName("V")
        self.X = QtWidgets.QLabel(self.centralwidget)
        self.X.setGeometry(QtCore.QRect(320, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.X.setFont(font)
        self.X.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.X.setAlignment(QtCore.Qt.AlignCenter)
        self.X.setObjectName("X")
        self.C = QtWidgets.QLabel(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(380, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.C.setFont(font)
        self.C.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.C.setAlignment(QtCore.Qt.AlignCenter)
        self.C.setObjectName("C")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(500, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.B.setFont(font)
        self.B.setStyleSheet("background-color: rgb(255, 202, 78);\n"
"color: rgb(209, 145, 41);")
        self.B.setAlignment(QtCore.Qt.AlignCenter)
        self.B.setObjectName("B")
        self.N = QtWidgets.QLabel(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(560, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.N.setFont(font)
        self.N.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.N.setAlignment(QtCore.Qt.AlignCenter)
        self.N.setObjectName("N")
        self.M = QtWidgets.QLabel(self.centralwidget)
        self.M.setGeometry(QtCore.QRect(620, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.M.setFont(font)
        self.M.setStyleSheet("background-color: rgb(244, 244, 47);\n"
"color: rgb(230, 195, 51);")
        self.M.setAlignment(QtCore.Qt.AlignCenter)
        self.M.setObjectName("M")
        self.Comma = QtWidgets.QLabel(self.centralwidget)
        self.Comma.setGeometry(QtCore.QRect(680, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Comma.setFont(font)
        self.Comma.setStyleSheet("background-color: rgb(203, 255, 58);\n"
"color: rgb(141, 176, 64);")
        self.Comma.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Comma.setObjectName("Comma")
        self.Dot = QtWidgets.QLabel(self.centralwidget)
        self.Dot.setGeometry(QtCore.QRect(740, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Dot.setFont(font)
        self.Dot.setStyleSheet("background-color: rgb(46, 245, 255);\n"
"color: rgb(37, 171, 208);")
        self.Dot.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Dot.setObjectName("Dot")
        self.Slash = QtWidgets.QLabel(self.centralwidget)
        self.Slash.setGeometry(QtCore.QRect(800, 460, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        self.Slash.setFont(font)
        self.Slash.setStyleSheet("background-color: rgb(33, 217, 147);\n"
"color: rgb(61, 175, 103);")
        self.Slash.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.Slash.setObjectName("Slash")
        self.vertical = QtWidgets.QLabel(self.centralwidget)
        self.vertical.setGeometry(QtCore.QRect(940, 350, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.vertical.setFont(font)
        self.vertical.setStyleSheet("color: rgb(155, 164, 172);")
        self.vertical.setObjectName("vertical")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(800, 490, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.question.setFont(font)
        self.question.setStyleSheet("color: rgb(61, 175, 103);")
        self.question.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.question.setObjectName("question")
        self.colon = QtWidgets.QLabel(self.centralwidget)
        self.colon.setGeometry(QtCore.QRect(780, 420, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.colon.setFont(font)
        self.colon.setStyleSheet("color: rgb(61, 175, 103);")
        self.colon.setObjectName("colon")
        self.doublequote = QtWidgets.QLabel(self.centralwidget)
        self.doublequote.setGeometry(QtCore.QRect(840, 425, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.doublequote.setFont(font)
        self.doublequote.setStyleSheet("color: rgb(61, 175, 103);")
        self.doublequote.setObjectName("doublequote")
        self.brace2 = QtWidgets.QLabel(self.centralwidget)
        self.brace2.setGeometry(QtCore.QRect(720, 300, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.brace2.setFont(font)
        self.brace2.setStyleSheet("color: rgb(61, 175, 103);")
        self.brace2.setAlignment(QtCore.Qt.AlignCenter)
        self.brace2.setObjectName("brace2")
        self.brace1 = QtWidgets.QLabel(self.centralwidget)
        self.brace1.setGeometry(QtCore.QRect(660, 300, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.brace1.setFont(font)
        self.brace1.setStyleSheet("color: rgb(37, 171, 208);")
        self.brace1.setAlignment(QtCore.Qt.AlignCenter)
        self.brace1.setObjectName("brace1")
        self.cage = QtWidgets.QLabel(self.centralwidget)
        self.cage.setGeometry(QtCore.QRect(310, 310, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.cage.setFont(font)
        self.cage.setStyleSheet("color: rgb(37, 171, 208);")
        self.cage.setObjectName("cage")
        self.dollar = QtWidgets.QLabel(self.centralwidget)
        self.dollar.setGeometry(QtCore.QRect(370, 310, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dollar.setFont(font)
        self.dollar.setStyleSheet("color: rgb(141, 176, 64);")
        self.dollar.setObjectName("dollar")
        self.cat = QtWidgets.QLabel(self.centralwidget)
        self.cat.setGeometry(QtCore.QRect(250, 310, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cat.setFont(font)
        self.cat.setStyleSheet("color: rgb(61, 175, 103);")
        self.cat.setObjectName("cat")
        self.exclamation = QtWidgets.QLabel(self.centralwidget)
        self.exclamation.setGeometry(QtCore.QRect(190, 310, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exclamation.setFont(font)
        self.exclamation.setStyleSheet("color: rgb(61, 175, 103);")
        self.exclamation.setObjectName("exclamation")
        self.curly1 = QtWidgets.QLabel(self.centralwidget)
        self.curly1.setGeometry(QtCore.QRect(800, 360, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.curly1.setFont(font)
        self.curly1.setStyleSheet("color: rgb(61, 175, 103);")
        self.curly1.setAlignment(QtCore.Qt.AlignCenter)
        self.curly1.setObjectName("curly1")
        self.curly2 = QtWidgets.QLabel(self.centralwidget)
        self.curly2.setGeometry(QtCore.QRect(860, 360, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.curly2.setFont(font)
        self.curly2.setStyleSheet("color: rgb(61, 175, 103);")
        self.curly2.setAlignment(QtCore.Qt.AlignCenter)
        self.curly2.setObjectName("curly2")
        self.star = QtWidgets.QLabel(self.centralwidget)
        self.star.setGeometry(QtCore.QRect(610, 310, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.star.setFont(font)
        self.star.setStyleSheet("color: rgb(141, 176, 64);")
        self.star.setObjectName("star")
        self.And = QtWidgets.QLabel(self.centralwidget)
        self.And.setGeometry(QtCore.QRect(550, 305, 20, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.And.setFont(font)
        self.And.setStyleSheet("color: rgb(230, 195, 51);")
        self.And.setObjectName("And")
        self.upward = QtWidgets.QLabel(self.centralwidget)
        self.upward.setGeometry(QtCore.QRect(490, 300, 21, 31))
        self.upward.setStyleSheet("color: rgb(209, 145, 41);")
        self.upward.setObjectName("upward")
        self.percent = QtWidgets.QLabel(self.centralwidget)
        self.percent.setGeometry(QtCore.QRect(420, 310, 47, 13))
        self.percent.setStyleSheet("color: rgb(209, 145, 41);")
        self.percent.setObjectName("percent")
        self.underline = QtWidgets.QLabel(self.centralwidget)
        self.underline.setGeometry(QtCore.QRect(780, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.underline.setFont(font)
        self.underline.setStyleSheet("color: rgb(61, 175, 103);")
        self.underline.setAlignment(QtCore.Qt.AlignCenter)
        self.underline.setObjectName("underline")
        self.plus = QtWidgets.QLabel(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(840, 300, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setStyleSheet("color: rgb(61, 175, 103);")
        self.plus.setAlignment(QtCore.Qt.AlignCenter)
        self.plus.setObjectName("plus")
        self.right = QtWidgets.QLabel(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(750, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.right.setFont(font)
        self.right.setStyleSheet("color: rgb(37, 171, 208);")
        self.right.setAlignment(QtCore.Qt.AlignCenter)
        self.right.setObjectName("right")
        self.left = QtWidgets.QLabel(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(690, 490, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.left.setFont(font)
        self.left.setStyleSheet("color: rgb(141, 176, 64);")
        self.left.setObjectName("left")
        self.cap = QtWidgets.QLabel(self.centralwidget)
        self.cap.setGeometry(QtCore.QRect(-5, 60, 31, 121))
        self.cap.setStyleSheet("background-color: rgb(124, 133, 216);")
        self.cap.setText("")
        self.cap.setObjectName("cap")
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(-10, 50, 1141, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Time.setFont(font)
        self.Time.setStyleSheet("color: rgb(44, 56, 97);")
        self.Time.setAlignment(QtCore.Qt.AlignCenter)
        self.Time.setObjectName("Time")
        self.RightPattern = QtWidgets.QLabel(self.centralwidget)
        self.RightPattern.setGeometry(QtCore.QRect(540, 120, 551, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.RightPattern.setFont(font)
        self.RightPattern.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(94, 110, 184);")
        self.RightPattern.setObjectName("RightPattern")
        self.LeftPattern = QtWidgets.QLabel(self.centralwidget)
        self.LeftPattern.setGeometry(QtCore.QRect(30, 120, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.LeftPattern.setFont(font)
        self.LeftPattern.setStyleSheet("background-color: rgb(201, 225, 255);\n"
"color: rgb(149, 160, 255);")
        self.LeftPattern.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LeftPattern.setObjectName("LeftPattern")
        self.stopped = QtWidgets.QListView(self.centralwidget)
        self.stopped.setGeometry(QtCore.QRect(30, 110, 1061, 81))
        self.stopped.setStyleSheet("background-color: rgb(188, 241, 255);")
        self.stopped.setObjectName("stopped")
        self.lstopped = QtWidgets.QLabel(self.centralwidget)
        self.lstopped.setGeometry(QtCore.QRect(40, 120, 1041, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lstopped.setFont(font)
        self.lstopped.setStyleSheet("color: rgb(53, 59, 153);\n"
"background-color: rgb(103, 113, 255);")
        self.lstopped.setAlignment(QtCore.Qt.AlignCenter)
        self.lstopped.setObjectName("lstopped")
        self.Errors = QtWidgets.QLabel(self.centralwidget)
        self.Errors.setGeometry(QtCore.QRect(-10, 80, 1141, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Errors.setFont(font)
        self.Errors.setStyleSheet("color: rgb(255, 138, 84);")
        self.Errors.setText("")
        self.Errors.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors.setObjectName("Errors")
        self.l = QtWidgets.QScrollArea(self.centralwidget)
        self.l.setGeometry(QtCore.QRect(120, 520, 241, 49))
        self.l.setStyleSheet("background-color: rgb(126, 189, 255);")
        self.l.setWidgetResizable(True)
        self.l.setObjectName("l")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 47))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Restart = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Restart.setFont(font)
        self.Restart.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(118, 220, 190);")
        self.Restart.setObjectName("Restart")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Restart)
        self.horizontalLayout.addWidget(self.Restart)
        self.l.setWidget(self.scrollAreaWidgetContents_2)
        self.r_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.r_2.setGeometry(QtCore.QRect(730, 520, 271, 49))
        self.r_2.setStyleSheet("background-color: rgb(126, 189, 255);")
        self.r_2.setWidgetResizable(True)
        self.r_2.setObjectName("r_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 269, 47))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Switch = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Switch.setFont(font)
        self.Switch.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(118, 220, 190);")
        self.Switch.setObjectName("Switch")
        self.buttonGroup.addButton(self.Switch)
        self.horizontalLayout_2.addWidget(self.Switch)
        self.r_2.setWidget(self.scrollAreaWidgetContents_3)
        self.KeyBoard_2 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_2.setGeometry(QtCore.QRect(110, 510, 251, 16))
        self.KeyBoard_2.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_2.setText("")
        self.KeyBoard_2.setObjectName("KeyBoard_2")
        self.KeyBoard_3 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_3.setGeometry(QtCore.QRect(120, 560, 241, 20))
        self.KeyBoard_3.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_3.setText("")
        self.KeyBoard_3.setObjectName("KeyBoard_3")
        self.KeyBoard_4 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_4.setGeometry(QtCore.QRect(730, 510, 271, 20))
        self.KeyBoard_4.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_4.setText("")
        self.KeyBoard_4.setObjectName("KeyBoard_4")
        self.KeyBoard_5 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_5.setGeometry(QtCore.QRect(730, 560, 271, 20))
        self.KeyBoard_5.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_5.setText("")
        self.KeyBoard_5.setObjectName("KeyBoard_5")
        self.KeyBoard_6 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_6.setGeometry(QtCore.QRect(360, 520, 16, 51))
        self.KeyBoard_6.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_6.setText("")
        self.KeyBoard_6.setObjectName("KeyBoard_6")
        self.KeyBoard_7 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_7.setGeometry(QtCore.QRect(110, 520, 16, 51))
        self.KeyBoard_7.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_7.setText("")
        self.KeyBoard_7.setObjectName("KeyBoard_7")
        self.KeyBoard_8 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_8.setGeometry(QtCore.QRect(990, 520, 16, 51))
        self.KeyBoard_8.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_8.setText("")
        self.KeyBoard_8.setObjectName("KeyBoard_8")
        self.KeyBoard_9 = QtWidgets.QLabel(self.centralwidget)
        self.KeyBoard_9.setGeometry(QtCore.QRect(720, 520, 16, 51))
        self.KeyBoard_9.setStyleSheet("background-color: rgb(126, 189, 255);\n"
"")
        self.KeyBoard_9.setText("")
        self.KeyBoard_9.setObjectName("KeyBoard_9")
        self.wList = QtWidgets.QListView(self.centralwidget)
        self.wList.setGeometry(QtCore.QRect(310, 200, 481, 321))
        self.wList.setStyleSheet("background-color: rgb(49, 57, 94);")
        self.wList.setObjectName("wList")
        self.widget = PlotWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(320, 210, 461, 301))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 210, 461, 301))
        self.label.setText("")
        self.label.setObjectName("label")
        self.switcher = QtWidgets.QListView(self.centralwidget)
        self.switcher.setGeometry(QtCore.QRect(310, 200, 481, 371))
        self.switcher.setStyleSheet("background-color: rgb(255, 202, 78);")
        self.switcher.setObjectName("switcher")
        self.aMode = QtWidgets.QRadioButton(self.centralwidget)
        self.aMode.setGeometry(QtCore.QRect(330, 210, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.aMode.setFont(font)
        self.aMode.setObjectName("aMode")
        self.fjMode = QtWidgets.QRadioButton(self.centralwidget)
        self.fjMode.setGeometry(QtCore.QRect(330, 420, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.fjMode.setFont(font)
        self.fjMode.setObjectName("fjMode")
        self.doSwitch = QtWidgets.QPushButton(self.centralwidget)
        self.doSwitch.setGeometry(QtCore.QRect(410, 510, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        self.doSwitch.setFont(font)
        self.doSwitch.setStyleSheet("background-color: rgb(174, 197, 110);\n"
"color: rgb(11, 75, 30);")
        self.doSwitch.setObjectName("doSwitch")
        self.rOrder = QtWidgets.QCheckBox(self.centralwidget)
        self.rOrder.setGeometry(QtCore.QRect(330, 460, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rOrder.setFont(font)
        self.rOrder.setObjectName("rOrder")
        self.KMode = QtWidgets.QRadioButton(self.centralwidget)
        self.KMode.setGeometry(QtCore.QRect(330, 370, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.KMode.setFont(font)
        self.KMode.setObjectName("KMode")
        self.sMode = QtWidgets.QRadioButton(self.centralwidget)
        self.sMode.setGeometry(QtCore.QRect(330, 270, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.sMode.setFont(font)
        self.sMode.setObjectName("sMode")
        self.lMode = QtWidgets.QRadioButton(self.centralwidget)
        self.lMode.setGeometry(QtCore.QRect(330, 320, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lMode.setFont(font)
        self.lMode.setObjectName("lMode")
        self.BackGround.raise_()
        self.KeyBoard.raise_()
        self.r_2.raise_()
        self.KeyBoard_4.raise_()
        self.l.raise_()
        self.KeyBoard_2.raise_()
        self.TextField.raise_()
        self.TextTyped.raise_()
        self.SpaceBar.raise_()
        self.Two.raise_()
        self.One.raise_()
        self.Backspace.raise_()
        self.Tab.raise_()
        self.Backslash.raise_()
        self.CAPS.raise_()
        self.Enter.raise_()
        self.LShift.raise_()
        self.RShift.raise_()
        self.Grave.raise_()
        self.Three.raise_()
        self.Four.raise_()
        self.Five.raise_()
        self.Six.raise_()
        self.Seven.raise_()
        self.Eight.raise_()
        self.Nine.raise_()
        self.Zero.raise_()
        self.Minus.raise_()
        self.Equality.raise_()
        self.Bracket2.raise_()
        self.Bracket1.raise_()
        self.P.raise_()
        self.O.raise_()
        self.I.raise_()
        self.U.raise_()
        self.Y.raise_()
        self.T.raise_()
        self.R.raise_()
        self.E.raise_()
        self.W.raise_()
        self.Q.raise_()
        self.A.raise_()
        self.D.raise_()
        self.S.raise_()
        self.G.raise_()
        self.F.raise_()
        self.H.raise_()
        self.J.raise_()
        self.K.raise_()
        self.L.raise_()
        self.Semicolon.raise_()
        self.Quote.raise_()
        self.Z.raise_()
        self.V.raise_()
        self.X.raise_()
        self.C.raise_()
        self.B.raise_()
        self.N.raise_()
        self.M.raise_()
        self.Comma.raise_()
        self.Dot.raise_()
        self.Slash.raise_()
        self.vertical.raise_()
        self.question.raise_()
        self.colon.raise_()
        self.doublequote.raise_()
        self.brace2.raise_()
        self.brace1.raise_()
        self.cage.raise_()
        self.dollar.raise_()
        self.cat.raise_()
        self.exclamation.raise_()
        self.curly1.raise_()
        self.curly2.raise_()
        self.star.raise_()
        self.And.raise_()
        self.upward.raise_()
        self.percent.raise_()
        self.underline.raise_()
        self.plus.raise_()
        self.right.raise_()
        self.left.raise_()
        self.cap.raise_()
        self.Time.raise_()
        self.tilde.raise_()
        self.RightPattern.raise_()
        self.LeftPattern.raise_()
        self.stopped.raise_()
        self.lstopped.raise_()
        self.Errors.raise_()
        self.KeyBoard_3.raise_()
        self.KeyBoard_5.raise_()
        self.KeyBoard_6.raise_()
        self.KeyBoard_7.raise_()
        self.KeyBoard_8.raise_()
        self.KeyBoard_9.raise_()
        self.wList.raise_()
        self.widget.raise_()
        self.label.raise_()
        self.switcher.raise_()
        self.aMode.raise_()
        self.fjMode.raise_()
        self.doSwitch.raise_()
        self.rOrder.raise_()
        self.KMode.raise_()
        self.sMode.raise_()
        self.lMode.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Two.setText(_translate("MainWindow", "2"))
        self.One.setText(_translate("MainWindow", "1"))
        self.tilde.setText(_translate("MainWindow", "~"))
        self.Backspace.setText(_translate("MainWindow", "<"))
        self.Tab.setText(_translate("MainWindow", "TAB"))
        self.Backslash.setText(_translate("MainWindow", "\\"))
        self.CAPS.setText(_translate("MainWindow", "CAPS"))
        self.Enter.setText(_translate("MainWindow", "ENTER"))
        self.LShift.setText(_translate("MainWindow", "SHIFT"))
        self.RShift.setText(_translate("MainWindow", "SHIFT"))
        self.Grave.setText(_translate("MainWindow", "`"))
        self.Three.setText(_translate("MainWindow", "3"))
        self.Four.setText(_translate("MainWindow", "4"))
        self.Five.setText(_translate("MainWindow", "5"))
        self.Six.setText(_translate("MainWindow", "6"))
        self.Seven.setText(_translate("MainWindow", "7"))
        self.Eight.setText(_translate("MainWindow", "8"))
        self.Nine.setText(_translate("MainWindow", "9"))
        self.Zero.setText(_translate("MainWindow", "0"))
        self.Minus.setText(_translate("MainWindow", "-"))
        self.Equality.setText(_translate("MainWindow", "="))
        self.Bracket2.setText(_translate("MainWindow", "]"))
        self.Bracket1.setText(_translate("MainWindow", "["))
        self.P.setText(_translate("MainWindow", "P"))
        self.O.setText(_translate("MainWindow", "O"))
        self.I.setText(_translate("MainWindow", "I"))
        self.U.setText(_translate("MainWindow", "U"))
        self.Y.setText(_translate("MainWindow", "Y"))
        self.T.setText(_translate("MainWindow", "T"))
        self.R.setText(_translate("MainWindow", "R"))
        self.E.setText(_translate("MainWindow", "E"))
        self.W.setText(_translate("MainWindow", "W"))
        self.Q.setText(_translate("MainWindow", "Q"))
        self.A.setText(_translate("MainWindow", "A"))
        self.D.setText(_translate("MainWindow", "D"))
        self.S.setText(_translate("MainWindow", "S"))
        self.G.setText(_translate("MainWindow", "G"))
        self.F.setText(_translate("MainWindow", "F"))
        self.H.setText(_translate("MainWindow", "H"))
        self.J.setText(_translate("MainWindow", "J"))
        self.K.setText(_translate("MainWindow", "K"))
        self.L.setText(_translate("MainWindow", "L"))
        self.Semicolon.setText(_translate("MainWindow", ";"))
        self.Quote.setText(_translate("MainWindow", "\'"))
        self.Z.setText(_translate("MainWindow", "Z"))
        self.V.setText(_translate("MainWindow", "V"))
        self.X.setText(_translate("MainWindow", "X"))
        self.C.setText(_translate("MainWindow", "C"))
        self.B.setText(_translate("MainWindow", "B"))
        self.N.setText(_translate("MainWindow", "N"))
        self.M.setText(_translate("MainWindow", "M"))
        self.Comma.setText(_translate("MainWindow", ","))
        self.Dot.setText(_translate("MainWindow", "."))
        self.Slash.setText(_translate("MainWindow", "/"))
        self.vertical.setText(_translate("MainWindow", "|"))
        self.question.setText(_translate("MainWindow", "?"))
        self.colon.setText(_translate("MainWindow", ":"))
        self.doublequote.setText(_translate("MainWindow", "\""))
        self.brace2.setText(_translate("MainWindow", ")"))
        self.brace1.setText(_translate("MainWindow", "("))
        self.cage.setText(_translate("MainWindow", "#"))
        self.dollar.setText(_translate("MainWindow", "$"))
        self.cat.setText(_translate("MainWindow", "@"))
        self.exclamation.setText(_translate("MainWindow", "!"))
        self.curly1.setText(_translate("MainWindow", "{"))
        self.curly2.setText(_translate("MainWindow", "{"))
        self.star.setText(_translate("MainWindow", "*"))
        self.And.setText(_translate("MainWindow", "&"))
        self.upward.setText(_translate("MainWindow", "^"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.underline.setText(_translate("MainWindow", "_"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.right.setText(_translate("MainWindow", ">"))
        self.left.setText(_translate("MainWindow", "<"))
        self.Time.setText(_translate("MainWindow", "Your result will be shown here"))
        self.RightPattern.setText(_translate("MainWindow", "Esc to stop"))
        self.LeftPattern.setText(_translate("MainWindow", "Space to start, "))
        self.lstopped.setText(_translate("MainWindow", "STOPPED"))
        self.Restart.setText(_translate("MainWindow", "Restart"))
        self.Switch.setText(_translate("MainWindow", "Switch mode"))
        self.aMode.setText(_translate("MainWindow", "ALPHABET MODE"))
        self.fjMode.setText(_translate("MainWindow", "FJ"))
        self.doSwitch.setText(_translate("MainWindow", "GO"))
        self.rOrder.setText(_translate("MainWindow", "Random order"))
        self.KMode.setText(_translate("MainWindow", "KANT"))
        self.sMode.setText(_translate("MainWindow", "SHORT WORDS"))
        self.lMode.setText(_translate("MainWindow", "LONG WORDS"))

from pyqtgraph import PlotWidget
